name: slither analyzer

on:
    push:
        branches: [main, develop]
    pull_request:

jobs:
    slither:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Run slither
              uses: crytic/slither-action@v0.3.0
              id: slither
              with:
                  node-version: 16
                  target: "."
                  sarif: results.sarif
                  fail-on: none
                  slither-args: --filter-path "test|node_modules|src/mocks"

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: ${{ steps.slither.outputs.sarif }}
